let A = 10;
let B = 20;
console.log('Valor original A = ' + A);
console.log('Valor original B = ' + B);
A = A + B;
B = A - B;
A = A - B;
console.log('Valor novo A = ' + A);
console.log('Valor novo B = ' + B);