Cores = ('vermelho','azul','verde','amarelo','preto')
novacor= Cores+('branco', 'cinza')
print(f"Qual o indice verde: {Cores.index('verde')}")
print(f"Quantas vezes azul aparece:{Cores.count('azul')}")
print(f"Novas cores: {novacor}")